### ISSUE TITLE
New feature - Compile & Run code before Submit

### ISSUE THREAD

**Issue by buiphukhuyen** [shi-yang/jnoj#122]
Hello,
I have researched some Online Judge systems as HackerRank,... and found that there are features Compile & Run code before Submit, feel very good. I don't know if JNOJ system can integrate this feature?

<img width="500" alt="Screenshot 2022-12-13 at 12 24 54" src="https://user-images.githubusercontent.com/43597300/207234222-1ffe905b-d513-4fe1-a2fa-0be8fef676cf.png">

<img width="500" alt="Screenshot 2022-12-13 at 12 21 51" src="https://user-images.githubusercontent.com/43597300/207234238-6afa2bc8-8436-4c71-9348-9a78c1e2b665.png">

I will further contribute and donate to the JNOJ system when building this feature.
Thanks very much!

**Comment by shi-yang** [comment]
Very good. I will release a new version that will bring this function. Here is a preview:
<img width="941" alt="20221214011240" src="https://user-images.githubusercontent.com/5102567/207399338-d2080fad-ff3a-40ab-872e-49b4232bfbf5.png">

**Comment by buiphukhuyen** [comment]
For this new version, do you share the same data and features as the old version? Or completely new construction?

**Comment by shi-yang** [comment]
Completely new construction. I will provide  upgrade guide and help with upgrades.
