### ISSUE TITLE
比赛中只能发一条公告

### ISSUE THREAD

**Issue by miiio** [shi-yang/jnoj#14]
contest_announcement这张表中的主键是contest_id，导致一场比赛只能发一条公告

**Comment by shi-yang** [comment]
现已修复。

使用 `git` 同步代码后，在项目目录下执行 `./yii migrate` 命令即可解决该问题。

PS: 运行该命令，会删除 contest_announcement 数据表的主键，并重新添加一个 id 字段作为主键。
