### ISSUE TITLE
./yii install 之后访问 http://localhost/jnoj/web/ Not Found

### ISSUE THREAD

**Issue by tesths** [shi-yang/jnoj#32]
一步一步按照 [安装教程](https://github.com/shi-yang/jnoj/blob/master/docs/install.md)
先安装了 LAMP 然后一步一步安装。
但是 ./yii install 没有报错。但之后访问 http://localhost/jnoj/web/ 显示
```
Not Found
The requested URL /jnoj/web/ was not found on this server.
Apache/2.4.18 (Ubuntu) Server at 127.0.0.1 Port 80
```

**Comment by eyanlong1** [comment]
要将jnoj放到apache的默认目录下，/var/www/html/
