### ISSUE TITLE
Bug：关于题目界面不能的提交状态不能正常显示颜色

### ISSUE THREAD

**Issue by yuuxeun** [shi-yang/jnoj#50]
![QQ截图20190918121739.png](https://i.loli.net/2019/09/18/RptLgohZBx28Cae.png)

**Comment by yuuxeun** [comment]
需要重新刷新界面才会显示正常的绿色

**Comment by shi-yang** [comment]
出现这个问题是我在比较时比较的是字符串 `Accepted`，然后因为汉化后比较不了才无法显示的。刚刚更新后就不是比较字符串 `Accepted` 了。
