### ISSUE TITLE
在配置子任务情况下有些题答案错误不显示错误的测试点, 后台出题和pologon出题都不能显示错误测试信息

### ISSUE THREAD

**Issue by yuuxeun** [shi-yang/jnoj#56]
在配置子任务情况下有些题答案错误不显示错误的测试点, 后台出题和pologon出题都不能显示错误测试信息
有些题目能正常显示
![image](https://user-images.githubusercontent.com/44895726/68195807-8466aa00-fff2-11e9-9473-7d9acf810dd8.png)
有些题目不能正常显示
![image](https://user-images.githubusercontent.com/44895726/68195831-91839900-fff2-11e9-939a-e3cbb2187794.png)

**Comment by shi-yang** [comment]
pologon出题还没有记录错误的测试点

**Comment by yuuxeun** [comment]
thinks 看得到已修复
