### ISSUE TITLE
如何默认显示比赛期间榜单

### ISSUE THREAD

**Issue by yuuxeun** [shi-yang/jnoj#57]
![image](https://user-images.githubusercontent.com/44895726/68545478-7f499680-0408-11ea-957d-513a46c11d75.png)

**Comment by shi-yang** [comment]
我改了下  https://github.com/shi-yang/jnoj/commit/0f2b78f2ac7e69e81fee3c69de0ae697942f9f25

改成默认显示比赛期间的榜单。
