### ISSUE TITLE
如何设置默认最大判题时间

### ISSUE THREAD

**Issue by yuuxeun** [shi-yang/jnoj#58]
如何设置默认最大判题时间?![image](https://user-images.githubusercontent.com/44895726/68682232-bdc58980-059f-11ea-9c3e-61eda42eaeaa.png)
由于jnoj使用的是hustoj判题机那么可以安装hustoj的配置文件来吗
![image](https://user-images.githubusercontent.com/44895726/68682588-54924600-05a0-11ea-8927-c70f9a93efa3.png)

**Comment by shi-yang** [comment]
这个 Polygon 的最大时间目前我还是写死在源码里的：

https://github.com/shi-yang/jnoj/blob/949d7813ccb57deefa826aded21ff94c2b692006/polygon/src/judge.c#L1094

把它改一下再到 `jnoj/polygon` 目录下执行 `make` 命令就好。
