### ISSUE TITLE
[功能]建议新增分数显示：在“测评结果”增加分数的显示，或单独增加一列分数也可以。

### ISSUE THREAD

**Issue by samxiaocd** [shi-yang/jnoj#63]
在以下界面的“测评结果”增加分数的显示，或单独增加一列分数也可以
![图片](https://user-images.githubusercontent.com/14372073/71434245-90333a80-271e-11ea-86be-b6b7c18d8d07.png)

如LG一样：
![图片](https://user-images.githubusercontent.com/14372073/71434225-7f82c480-271e-11ea-9ec3-aa57b8d73207.png)

**Comment by shi-yang** [comment]
这个你到后台-设置-启用 OI 模式就能看到了。

**Comment by samxiaocd** [comment]
改为OI模式后，看到了
![Uploading 图片.png…]()
