### ISSUE TITLE
关于不能删除注册账户的咨询

### ISSUE THREAD

**Issue by Dreamjjh** [shi-yang/jnoj#72]
系统里面注册账户太多了，想删除一些。但是提示说无法删除，请问怎么解决这个问题？

**Comment by shi-yang** [comment]
关于这个地方我的想法是这样的，虽然会存在一定的冗余数据，看着可能有点碍眼，但其实也占用不了什么空间，没有必要对其进行删除。而且，删除的过程也带来一定的管理成本，比如要一个个地判断它是不是无用的注册用户。

目前解决这个问题的办法就是限制用户注册，比如邀请码机制，或者提供关闭注册的功能。这个功能会近期增加。

**Comment by Dreamjjh** [comment]
这样确实可以减少数据库数据冗余，我在数据库里面看了一下，数据库表格还不少，删除账户涉及到的表格有好几个，确实麻烦。另外，建议优化一下系统的错误提醒，比方说登录时，用户名错了，验证失败。出题系统里面，没有提交.in文件，直接点击运行，系统会一直卡正在评测，重启./ploygon都无法解决。
